services:
    # app:
    #   container_name: api-node-fastify
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   command: sh -c "npm install && npm run dev"
    #   ports:
    #     - "3000:3000"
    #   environment:
    #     # Ajuste conforme suas variáveis de conexão
    #     NODE_ENV: development
    #     DB_HOST: mysql
    #     DB_PORT: 3306
    #     DB_USER: appuser
    #     DB_PASSWORD: appsecret
    #     DB_NAME: appdb
    #   depends_on:
    #     mysql:
    #       condition: service_healthy
    #   volumes:
    #     - ./:/usr/src/app
    #   networks:
    #     - app-net

    mysql:
        image: mysql:8.0
        container_name: mysql-db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: r00ts3cr3t
            MYSQL_DATABASE: api
            MYSQL_USER: apiuser
            MYSQL_PASSWORD: apis3cr3t
            TZ: America/Sao_Paulo
        ports:
            - '3309:3306'
        healthcheck:
            test:
                [
                    'CMD',
                    'mysqladmin',
                    'ping',
                    '-h',
                    '127.0.0.1',
                    '-uappuser',
                    '-pappsecret',
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-net

networks:
    app-net:
        driver: bridge

volumes:
    mysql_data:
